# coding: utf-8
"""PostgreSQL-readiness Unit 5-A: real PostgreSQL integration gate.

Runs only when ``SGAA_PG_TEST_URL`` supplies administrative access to a local
PostgreSQL server (PG 15+); otherwise the whole module skips.  The lane NEVER
provisions into, resets or drops schemas of the database named in that URL:
for every test it creates uniquely named ``sgaa_u5a_test_*`` databases, records
them in a session-owned registry, and drops only those during teardown.  If the
configured role cannot CREATE DATABASE the module skips clearly.  Every test
then works inside its own throwaway schema of a fixture-owned database -- the
explicit CLI lane provisions a fixture-owned empty database.

The gate proves, on a real server:

1. provisioning DDL completes;
2. a second provision is a safe no-op when the schema matches;
3. partial/incompatible schemas fail closed without destructive repair;
4. every required table exists;
5. identity is ``GENERATED BY DEFAULT`` (explicit IDs accepted) and generated
   identity works, including advancing the sequence after explicit loading;
6. all material and the composite foreign key compile and enforce;
7. the partial unique predicates enforce;
8. JSON text checks are PG15-compatible and refuse malformed input as
   constraint violations;
9. the timestamp helper/default is exact text UTC at second resolution;
10. all eleven triggers compile and enforce positive and negative cases;
11. ``validate_pg_schema`` passes a valid schema and is read-only;
12. material schema mutations are detected by the validator;
13. psycopg diagnostics carry the explicit expected constraint names.
"""
import os
import re
import secrets
import subprocess
import sys
import time
from datetime import datetime, timedelta, timezone
from pathlib import Path
from urllib.parse import urlsplit, urlunsplit

import pytest

PG_URL = os.environ.get("SGAA_PG_TEST_URL", "").strip()

#: Strong prefix every database created by this lane carries.  Destructive
#: operations are permitted only for databases with this prefix AND registered
#: by the current test session.
DISPOSABLE_DATABASE_PREFIX = "sgaa_u5a_test_"

#: Databases this lane must never create, modify or drop.
PROTECTED_DATABASES = frozenset({"postgres", "template0", "template1"})

pytestmark = pytest.mark.skipif(
    not PG_URL,
    reason="SGAA_PG_TEST_URL is not configured (local PostgreSQL admin access required)",
)

psycopg = pytest.importorskip("psycopg")

REPO_ROOT = Path(__file__).resolve().parents[1]


def _pg():
    from app import pg_schema

    return pg_schema


def _connect(url, *, autocommit=False):
    return psycopg.connect(url, prepare_threshold=None, autocommit=autocommit)


def _database_url(database):
    parts = urlsplit(PG_URL)
    return urlunsplit((parts.scheme, parts.netloc, "/" + database, "", ""))


class _DisposableDatabaseRegistry:
    """Session-owned creator and sole destroyer of test databases.

    ``SGAA_PG_TEST_URL`` is treated as server/admin access only.  This registry
    is the hard safety boundary: :meth:`drop` refuses protected server
    databases, names without the disposable prefix, and any database this test
    session did not create.
    """

    def __init__(self, admin_url):
        self._admin_url = admin_url
        self._admin = None
        self._owned = set()

    def admin_connection(self):
        if self._admin is None or self._admin.closed:
            self._admin = _connect(self._admin_url, autocommit=True)
        return self._admin

    def create(self, label=""):
        database = f"{DISPOSABLE_DATABASE_PREFIX}{label}{secrets.token_hex(6)}"
        with self.admin_connection().cursor() as cursor:
            cursor.execute(f'CREATE DATABASE "{database}"')
        self._owned.add(database)
        return database, _database_url(database)

    def drop(self, database):
        if database in PROTECTED_DATABASES:
            raise AssertionError(f"refusing to drop protected database {database!r}")
        if not database.startswith(DISPOSABLE_DATABASE_PREFIX):
            raise AssertionError(
                f"refusing to drop {database!r}: not a "
                f"{DISPOSABLE_DATABASE_PREFIX!r} disposable database"
            )
        if database not in self._owned:
            raise AssertionError(
                f"refusing to drop {database!r}: not created by this test session"
            )
        with self.admin_connection().cursor() as cursor:
            cursor.execute(f'DROP DATABASE IF EXISTS "{database}" WITH (FORCE)')
        self._owned.discard(database)

    def close(self):
        failures = []
        for database in sorted(self._owned):
            try:
                self.drop(database)
            except Exception as exc:  # pragma: no cover - teardown reporting
                failures.append((database, repr(exc)))
        if self._admin is not None and not self._admin.closed:
            self._admin.close()
        assert not failures, f"could not drop fixture-owned databases: {failures!r}"


def _scalar(connection, sql, params=None):
    with connection.cursor() as cursor:
        if params is None:
            cursor.execute(sql)
        else:
            cursor.execute(sql, params)
        return cursor.fetchone()[0]


def _count(connection, table):
    return int(_scalar(connection, f"SELECT count(*) FROM {table}"))


def _catalog_snapshot(connection):
    queries = {
        "tables": "SELECT c.relname FROM pg_catalog.pg_class c "
        "JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace "
        "WHERE n.nspname=current_schema() AND c.relkind IN ('r','p') ORDER BY 1",
        "indexes": "SELECT c.relname FROM pg_catalog.pg_index i "
        "JOIN pg_catalog.pg_class c ON c.oid=i.indexrelid "
        "JOIN pg_catalog.pg_class t ON t.oid=i.indrelid "
        "JOIN pg_catalog.pg_namespace n ON n.oid=t.relnamespace "
        "WHERE n.nspname=current_schema() ORDER BY 1",
        "constraints": "SELECT con.conname FROM pg_catalog.pg_constraint con "
        "JOIN pg_catalog.pg_class c ON c.oid=con.conrelid "
        "JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace "
        "WHERE n.nspname=current_schema() ORDER BY 1",
        "triggers": "SELECT t.tgname FROM pg_catalog.pg_trigger t "
        "JOIN pg_catalog.pg_class c ON c.oid=t.tgrelid "
        "JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace "
        "WHERE n.nspname=current_schema() AND NOT t.tgisinternal ORDER BY 1",
        "functions": "SELECT p.proname FROM pg_catalog.pg_proc p "
        "JOIN pg_catalog.pg_namespace n ON n.oid=p.pronamespace "
        "WHERE n.nspname=current_schema() ORDER BY 1",
        "meta": "SELECT id, schema_epoch, schema_version, contract_sha256, applied_at "
        "FROM pg_schema_meta ORDER BY id",
    }
    snapshot = {}
    for key, sql in queries.items():
        with connection.cursor() as cursor:
            cursor.execute(sql)
            snapshot[key] = [tuple(row) for row in cursor.fetchall()]
    return snapshot


# ---------------------------------------------------------------------------
# fixtures
# ---------------------------------------------------------------------------


@pytest.fixture(scope="session")
def disposable_databases():
    """Admin access plus the hard ownership boundary for every test database."""
    registry = _DisposableDatabaseRegistry(PG_URL)
    try:
        try:
            registry.admin_connection()
        except psycopg.Error as exc:
            pytest.skip(
                "SGAA_PG_TEST_URL is not usable as a local PostgreSQL admin "
                f"connection: {exc}"
            )
        try:
            probe, _ = registry.create("probe_")
        except psycopg.Error as exc:
            pytest.skip(
                "SGAA_PG_TEST_URL lacks CREATE DATABASE privilege; this lane "
                f"needs local PostgreSQL admin access: {exc}"
            )
        registry.drop(probe)
        yield registry
    finally:
        registry.close()


@pytest.fixture(scope="module")
def disposable_database(disposable_databases):
    """One fixture-owned disposable database shared by the module's schemas."""
    database, url = disposable_databases.create("main_")
    try:
        yield url
    finally:
        disposable_databases.drop(database)


@pytest.fixture()
def empty_database(disposable_databases):
    """A fixture-owned, never-provisioned disposable database."""
    database, url = disposable_databases.create("empty_")
    try:
        yield url
    finally:
        disposable_databases.drop(database)


@pytest.fixture()
def schema_conn(disposable_database):
    connection = _connect(disposable_database)
    schema = "t_" + secrets.token_hex(6)
    with connection.cursor() as cursor:
        cursor.execute(f'CREATE SCHEMA "{schema}"')
        cursor.execute(f'SET search_path TO "{schema}"')
    connection.commit()
    try:
        yield connection, schema
    finally:
        connection.rollback()
        with connection.cursor() as cursor:
            cursor.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
        connection.commit()
        connection.close()


@pytest.fixture()
def provisioned_schema(schema_conn):
    connection, schema = schema_conn
    pg = _pg()
    result = pg.provision_pg_schema(connection)
    connection.commit()
    assert result["status"] == "provisioned"
    return connection, schema


@pytest.fixture(scope="module")
def provisioned_public(disposable_database):
    """The baseline provisioned into the owned database's public schema.

    The database is fixture-owned and dropped by the session registry; no
    schema of the externally supplied SGAA_PG_TEST_URL database is touched.
    """
    pg = _pg()
    connection = _connect(disposable_database)
    try:
        result = pg.provision_pg_schema(connection)
        connection.commit()
        assert result["status"] == "provisioned"
        yield disposable_database
    finally:
        connection.close()


def _seed_course_matrix_turma(cur, suffix="U5A"):
    cur.execute(
        "INSERT INTO cursos(nome,codigo,duracao_periodos) "
        "VALUES(%s,%s,8) RETURNING id",
        (f"Curso {suffix}", f"CURSO-{suffix}"),
    )
    course = cur.fetchone()[0]
    cur.execute(
        "INSERT INTO matrizes_atividades(curso_id,nome) "
        "VALUES(%s,%s) RETURNING id",
        (course, f"Matriz {suffix}"),
    )
    matrix = cur.fetchone()[0]
    cur.execute(
        "INSERT INTO turmas(nome,numero,curso_id,ano_inicio,semestre_inicio,"
        "codigo,matriz_id) VALUES(%s,1,%s,2026,1,%s,%s) RETURNING id",
        (f"Turma {suffix}", course, f"TURMA-{suffix}", matrix),
    )
    turma = cur.fetchone()[0]
    return course, matrix, turma


def _seed_base_version(cur, eixo="AAC", numero=1, predecessor=None, conceito="Base U5A"):
    cur.execute(
        "INSERT INTO atividade_base(nome_conceito) VALUES(%s) RETURNING id",
        (conceito,),
    )
    base = cur.fetchone()[0]
    version = _insert_version(cur, base, eixo, numero, predecessor)
    return base, version


def _insert_version(cur, base, eixo, numero, predecessor=None):
    cur.execute(
        "INSERT INTO atividade_versao(atividade_base_id,eixo,numero_versao,status,"
        "versao_anterior_id) VALUES(%s,%s,%s,'ativa',%s) RETURNING id",
        (base, eixo, numero, predecessor),
    )
    return cur.fetchone()[0]


def _seed_aluno(cur, matricula="U5A-1"):
    cur.execute(
        "INSERT INTO alunos(nome,matricula) VALUES('Aluno U5A',%s) RETURNING id",
        (matricula,),
    )
    return cur.fetchone()[0]


def _seed_requisicao(cur, version, aluno=None):
    cur.execute(
        "INSERT INTO requisicoes(aluno_id,atividade_versao_id,data_solicitacao,"
        "data_evento,horas_solicitadas,status,regra_snapshot_json) "
        "VALUES(%s,%s,'2026-01-10 10:00:00','2026-01-10 10:00:00',4,'Pendente',"
        "'{\"schema_version\":\"prod-1-request-v2\"}') RETURNING id",
        (aluno, version),
    )
    return cur.fetchone()[0]


def _probe_sqlstate(connection, sql, params=None, *, savepoint="u5a_probe"):
    """Execute a statement expected to fail without discarding prior setup."""
    connection.execute(f"SAVEPOINT {savepoint}")
    try:
        with connection.cursor() as cursor:
            cursor.execute(sql, params)
    except Exception as exc:
        connection.execute(f"ROLLBACK TO SAVEPOINT {savepoint}")
        connection.execute(f"RELEASE SAVEPOINT {savepoint}")
        return exc
    connection.execute(f"RELEASE SAVEPOINT {savepoint}")
    raise AssertionError(f"statement unexpectedly succeeded: {sql}")


def _assert_refused(connection, table, sql, params=None):
    pg = _pg()
    before = _count(connection, table)
    error = _probe_sqlstate(connection, sql, params)
    assert getattr(error, "sqlstate", None) == pg.PG_BUSINESS_RULE_SQLSTATE, (
        f"expected {pg.PG_BUSINESS_RULE_SQLSTATE}, got {error!r}"
    )
    assert _count(connection, table) == before
    return error


def _assert_constraint_violation(
    connection, sql, params, error_type, constraint_name
):
    error = _probe_sqlstate(connection, sql, params)
    assert isinstance(error, error_type), error
    assert error.diag.constraint_name == constraint_name, error.diag.constraint_name
    return error


# ---------------------------------------------------------------------------
# 1-4. provisioning, idempotency, fail-closed, table census
# ---------------------------------------------------------------------------


def test_provisioning_completes_and_second_provision_is_idempotent(schema_conn):
    connection, schema = schema_conn
    pg = _pg()
    first = pg.provision_pg_schema(connection)
    connection.commit()
    assert first["status"] == "provisioned"
    tables = {
        row[0]
        for row in connection.execute(
            "SELECT c.relname FROM pg_catalog.pg_class c "
            "JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace "
            "WHERE n.nspname=current_schema() AND c.relkind IN ('r','p')"
        ).fetchall()
    }
    assert tables == set(pg.PG_SCHEMA_TABLES)
    assert len(tables) == 34
    triggers = {
        row[0]
        for row in connection.execute(
            "SELECT t.tgname FROM pg_catalog.pg_trigger t "
            "JOIN pg_catalog.pg_class c ON c.oid=t.tgrelid "
            "JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace "
            "WHERE n.nspname=current_schema() AND NOT t.tgisinternal"
        ).fetchall()
    }
    assert triggers == {trigger["name"] for trigger in pg.PG_TRIGGERS}
    indexes = {
        row[0]
        for row in connection.execute(
            "SELECT c.relname FROM pg_catalog.pg_index i "
            "JOIN pg_catalog.pg_class c ON c.oid=i.indexrelid "
            "JOIN pg_catalog.pg_class t ON t.oid=i.indrelid "
            "JOIN pg_catalog.pg_namespace n ON n.oid=t.relnamespace "
            "WHERE n.nspname=current_schema()"
        ).fetchall()
    }
    assert set(pg.PG_EXPLICIT_INDEXES) <= indexes
    snapshot = _catalog_snapshot(connection)
    second = pg.provision_pg_schema(connection)
    connection.commit()
    assert second["status"] == "already_provisioned"
    assert _catalog_snapshot(connection) == snapshot
    pg.validate_pg_schema(connection)


def test_partial_or_incompatible_schema_fails_closed(schema_conn):
    connection, schema = schema_conn
    pg = _pg()
    with connection.cursor() as cursor:
        cursor.execute("CREATE TABLE usuarios(id integer)")
    connection.commit()
    with pytest.raises(pg.PostgresSchemaError) as excinfo:
        pg.provision_pg_schema(connection)
    connection.rollback()
    assert "usuarios" in str(excinfo.value) or "provision" in str(excinfo.value).lower()
    tables = {
        row[0]
        for row in connection.execute(
            "SELECT c.relname FROM pg_catalog.pg_class c "
            "JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace "
            "WHERE n.nspname=current_schema() AND c.relkind IN ('r','p')"
        ).fetchall()
    }
    assert tables == {"usuarios"}


def test_empty_database_cli_provision_is_explicit_and_idempotent(disposable_databases):
    pg = _pg()
    database, url = disposable_databases.create("cli_")
    try:
        env = dict(os.environ)
        env["DATABASE_URL"] = url
        first = subprocess.run(
            [sys.executable, "-B", "-m", "app.pg_schema", "provision"],
            cwd=str(REPO_ROOT),
            env=env,
            capture_output=True,
            text=True,
            timeout=300,
        )
        assert first.returncode == 0, first.stdout + first.stderr
        assert "provisioned" in first.stdout
        second = subprocess.run(
            [sys.executable, "-B", "-m", "app.pg_schema", "provision"],
            cwd=str(REPO_ROOT),
            env=env,
            capture_output=True,
            text=True,
            timeout=300,
        )
        assert second.returncode == 0, second.stdout + second.stderr
        assert "already_provisioned" in second.stdout
        validation = subprocess.run(
            [sys.executable, "-B", "-m", "app.pg_schema", "validate"],
            cwd=str(REPO_ROOT),
            env=env,
            capture_output=True,
            text=True,
            timeout=300,
        )
        assert validation.returncode == 0, validation.stdout + validation.stderr
        sqlite_env = dict(os.environ)
        sqlite_env["DATABASE_URL"] = "sqlite:///database.db"
        refused = subprocess.run(
            [sys.executable, "-B", "-m", "app.pg_schema", "provision"],
            cwd=str(REPO_ROOT),
            env=sqlite_env,
            capture_output=True,
            text=True,
            timeout=120,
        )
        assert refused.returncode != 0
        assert "postgres" in (refused.stdout + refused.stderr).lower()
    finally:
        disposable_databases.drop(database)


# ---------------------------------------------------------------------------
# 5. identity: explicit IDs, generated IDs, sequence advance
# ---------------------------------------------------------------------------


def test_identity_is_by_default_and_sequence_can_advance(provisioned_schema):
    connection, schema = provisioned_schema
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT a.attidentity FROM pg_catalog.pg_attribute a "
            "JOIN pg_catalog.pg_class c ON c.oid=a.attrelid "
            "JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace "
            "WHERE n.nspname=current_schema() AND c.relname='usuarios' "
            "AND a.attname='id'"
        )
        assert cursor.fetchone()[0] == "d"
        cursor.execute(
            "INSERT INTO usuarios(id,nome,email,senha,tipo) "
            "VALUES(9000,'Explicit','explicit@u5a.test','hash','admin')"
        )
        cursor.execute(
            "INSERT INTO usuarios(nome,email,senha,tipo) "
            "VALUES('Generated','generated@u5a.test','hash','admin') RETURNING id"
        )
        generated = cursor.fetchone()[0]
        assert generated != 9000
        cursor.execute("SELECT pg_get_serial_sequence('usuarios','id')")
        sequence = cursor.fetchone()[0]
        assert sequence
        cursor.execute(f"SELECT setval('{sequence}', (SELECT MAX(id) FROM usuarios))")
        cursor.execute(
            "INSERT INTO usuarios(nome,email,senha,tipo) "
            "VALUES('After','after@u5a.test','hash','admin') RETURNING id"
        )
        assert cursor.fetchone()[0] == 9001
    connection.commit()


# ---------------------------------------------------------------------------
# 6. FKs: material actions and composite FK
# ---------------------------------------------------------------------------


def test_foreign_keys_and_composite_fk_compile_and_enforce(provisioned_schema):
    connection, schema = provisioned_schema
    with connection.cursor() as cursor:
        course, matrix, turma = _seed_course_matrix_turma(cursor)
        base_one, version_one = _seed_base_version(cursor, conceito="Base U5A 1")
        base_two, version_two = _seed_base_version(cursor, conceito="Base U5A 2")
        base_three, version_three = _seed_base_version(cursor, conceito="Base U5A 3")
        cursor.execute(
            "INSERT INTO matriz_atividade_versao_item(matriz_id,atividade_base_id,"
            "atividade_versao_id) VALUES(%s,%s,%s)",
            (matrix, base_one, version_one),
        )
    # (version_two, base_three) satisfies both (matriz, base) / (matriz, versao)
    # uniqueness but not the composite FK to atividade_versao(id, atividade_base_id).
    _assert_constraint_violation(
        connection,
        "INSERT INTO matriz_atividade_versao_item(matriz_id,atividade_base_id,"
        "atividade_versao_id) VALUES(%s,%s,%s)",
        (matrix, base_three, version_two),
        psycopg.errors.ForeignKeyViolation,
        "fk_matriz_atividade_versao_item_versao_base",
    )
    _assert_constraint_violation(
        connection,
        "DELETE FROM matrizes_atividades WHERE id=%s",
        (matrix,),
        (psycopg.errors.ForeignKeyViolation, psycopg.errors.RestrictViolation),
        "fk_turmas_matriz_id",
    )
    connection.rollback()


# ---------------------------------------------------------------------------
# 7. partial unique predicates
# ---------------------------------------------------------------------------


def test_partial_unique_index_predicates_enforce(provisioned_schema):
    connection, schema = provisioned_schema
    with connection.cursor() as cursor:
        cursor.execute(
            "INSERT INTO configuracoes_presets(tipo,preset_id,titulo,is_default) "
            "VALUES('emails',1,'A',1)"
        )
    _assert_constraint_violation(
        connection,
        "INSERT INTO configuracoes_presets(tipo,preset_id,titulo,is_default) "
        "VALUES('emails',2,'B',1)",
        None,
        psycopg.errors.UniqueViolation,
        "ux_configuracoes_presets_default",
    )
    with connection.cursor() as cursor:
        cursor.execute(
            "INSERT INTO configuracoes_presets(tipo,preset_id,titulo,is_default) "
            "VALUES('emails',3,'C',0),('emails',4,'D',0)"
        )

    with connection.cursor() as cursor:
        course, matrix, turma = _seed_course_matrix_turma(cursor)
        base, version = _seed_base_version(cursor)
        aluno = _seed_aluno(cursor)
        requisicao = _seed_requisicao(cursor, version, aluno)
        cursor.execute(
            "INSERT INTO requisicao_email_eventos(requisicao_id,aluno_id,"
            "status_decisao,horas_solicitadas,data_solicitacao,decidido_em) "
            "VALUES(%s,%s,'Deferida',4,'2026-01-10 10:00:00','2026-01-11 10:00:00')",
            (requisicao, aluno),
        )
    _assert_constraint_violation(
        connection,
        "INSERT INTO requisicao_email_eventos(requisicao_id,aluno_id,"
        "status_decisao,horas_solicitadas,data_solicitacao,decidido_em) "
        "VALUES(%s,%s,'Deferida',4,'2026-01-10 10:00:00','2026-01-11 11:00:00')",
        (requisicao, aluno),
        psycopg.errors.UniqueViolation,
        "ux_req_email_eventos_pendente",
    )
    with connection.cursor() as cursor:
        cursor.execute(
            "INSERT INTO requisicao_email_eventos(requisicao_id,aluno_id,"
            "status_decisao,horas_solicitadas,data_solicitacao,decidido_em,estado) "
            "VALUES(%s,%s,'Indeferida',4,'2026-01-10 10:00:00',"
            "'2026-01-11 12:00:00','sent')",
            (requisicao, aluno),
        )

    with connection.cursor() as cursor:
        cursor.execute(
            "INSERT INTO admin_arquivos(titulo,filename,provider,storage_status,"
            "remote_file_id) VALUES('A','a.pdf','google','failed','remote-1')"
        )
    _assert_constraint_violation(
        connection,
        "INSERT INTO admin_arquivos(titulo,filename,provider,storage_status,"
        "remote_file_id) VALUES('B','b.pdf','google','failed','remote-1')",
        None,
        psycopg.errors.UniqueViolation,
        "ux_admin_arquivos_provider_remote_file",
    )
    with connection.cursor() as cursor:
        cursor.execute(
            "INSERT INTO admin_arquivos(titulo,filename,provider,storage_status,"
            "remote_file_id) VALUES('C','c.pdf','google','failed',NULL),"
            "('D','d.pdf','google','failed',NULL)"
        )
        cursor.execute(
            "INSERT INTO admin_arquivos(titulo,filename,provider,storage_status,"
            "operation_key) VALUES('E','e.pdf','google','failed','op-adm')"
        )
    _assert_constraint_violation(
        connection,
        "INSERT INTO admin_arquivos(titulo,filename,provider,storage_status,"
        "operation_key) VALUES('F','f.pdf','google','failed','op-adm')",
        None,
        psycopg.errors.UniqueViolation,
        "ux_admin_arquivos_operation_key",
    )
    with connection.cursor() as cursor:
        cursor.execute(
            "INSERT INTO admin_arquivos(titulo,filename,provider,storage_status,"
            "operation_key) VALUES('G','g.pdf','google','failed',NULL),"
            "('H','h.pdf','google','failed',NULL)"
        )

    with connection.cursor() as cursor:
        course, matrix, turma = _seed_course_matrix_turma(cursor, "U5A-2")
        base, version = _seed_base_version(cursor, conceito="Base U5A 2")
        requisicao = _seed_requisicao(cursor, version)
        cursor.execute(
            "INSERT INTO requisicao_arquivos(requisicao_id,filename,operation_key) "
            "VALUES(%s,'a.pdf','op-1')",
            (requisicao,),
        )
    _assert_constraint_violation(
        connection,
        "INSERT INTO requisicao_arquivos(requisicao_id,filename,operation_key) "
        "VALUES(%s,'b.pdf','op-1')",
        (requisicao,),
        psycopg.errors.UniqueViolation,
        "ux_req_arquivos_operation_key",
    )
    with connection.cursor() as cursor:
        cursor.execute(
            "INSERT INTO requisicao_arquivos(requisicao_id,filename,operation_key) "
            "VALUES(%s,'c.pdf',NULL),(%s,'d.pdf',NULL)",
            (requisicao, requisicao),
        )
        course, matrix, turma = _seed_course_matrix_turma(cursor, "U5A-3")
        base, version = _seed_base_version(cursor, conceito="Base U5A 3")
        requisicao = _seed_requisicao(cursor, version)
        cursor.execute(
            "INSERT INTO requisicao_arquivos(requisicao_id,filename,provider,"
            "remote_file_id) VALUES(%s,'r.pdf','google','remote-op')",
            (requisicao,),
        )
    _assert_constraint_violation(
        connection,
        "INSERT INTO requisicao_arquivos(requisicao_id,filename,provider,"
        "remote_file_id) VALUES(%s,'r2.pdf','google','remote-op')",
        (requisicao,),
        psycopg.errors.UniqueViolation,
        "ux_req_arquivos_provider_remote_file",
    )
    connection.rollback()


# ---------------------------------------------------------------------------
# 8. JSON checks (PG15-compatible)
# ---------------------------------------------------------------------------


def test_json_text_checks_are_pg15_compatible(provisioned_schema):
    connection, schema = provisioned_schema
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT pg_get_constraintdef(oid, true) FROM pg_constraint "
            "WHERE conname='ck_atividade_versao_documentos_json'"
        )
        definition = cursor.fetchone()[0]
        assert "sgaa_json_is_valid" in definition
        assert "IS JSON" not in definition
        base, version = _seed_base_version(cursor)
        cursor.execute(
            "INSERT INTO atividade_versao(atividade_base_id,eixo,numero_versao,status,"
            "documentos_json) VALUES(%s,'AAC',2,'ativa','[1,2,3]')",
            (base,),
        )
        cursor.execute(
            "INSERT INTO atividade_versao(atividade_base_id,eixo,numero_versao,status,"
            "documentos_json) VALUES(%s,'AEU',3,'ativa',NULL)",
            (base,),
        )
    _assert_constraint_violation(
        connection,
        "INSERT INTO atividade_versao(atividade_base_id,eixo,numero_versao,"
        "status,documentos_json) VALUES(%s,'AAC',4,'ativa','{invalid')",
        (base,),
        psycopg.errors.CheckViolation,
        "ck_atividade_versao_documentos_json",
    )

    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT pg_get_constraintdef(oid, true) FROM pg_constraint "
            "WHERE conname='ck_requisicoes_regra_snapshot_json'"
        )
        definition = cursor.fetchone()[0]
        assert "sgaa_json_is_valid" in definition
        assert "sgaa_json_is_object" in definition
        assert "IS JSON" not in definition
        base, version = _seed_base_version(cursor, conceito="Base snapshot")
        cursor.execute(
            "INSERT INTO requisicoes(atividade_versao_id,data_solicitacao,data_evento,"
            "horas_solicitadas,status,regra_snapshot_json) VALUES(%s,"
            "'2026-01-10 10:00:00','2026-01-10 10:00:00',4,'Pendente','{}')",
            (version,),
        )
    insert_prefix = (
        "INSERT INTO requisicoes(atividade_versao_id,data_solicitacao,data_evento,"
        "horas_solicitadas,status,regra_snapshot_json) VALUES(%s,"
        "'2026-01-10 10:00:00','2026-01-10 10:00:00',4,'Pendente',"
    )
    for invalid_literal in ("'[]'", "'\"scalar\"'", "'not-json'"):
        _assert_constraint_violation(
            connection,
            insert_prefix + invalid_literal + ")",
            (version,),
            psycopg.errors.CheckViolation,
            "ck_requisicoes_regra_snapshot_json",
        )
    null_error = _probe_sqlstate(
        connection, insert_prefix + "NULL)", (version,)
    )
    assert isinstance(null_error, psycopg.errors.NotNullViolation)
    connection.rollback()


# ---------------------------------------------------------------------------
# 9. timestamp helper / defaults
# ---------------------------------------------------------------------------


def test_timestamp_helper_is_utc_text_seconds_and_lexically_ordered(provisioned_schema):
    connection, schema = provisioned_schema
    with connection.cursor() as cursor:
        cursor.execute("SET TIME ZONE 'America/Sao_Paulo'")
        cursor.execute("SELECT sgaa_utcnow_text()")
        value = cursor.fetchone()[0]
        assert re.fullmatch(r"\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}", value)
        parsed = datetime.strptime(value, "%Y-%m-%d %H:%M:%S").replace(
            tzinfo=timezone.utc
        )
        assert abs(
            (parsed - datetime.now(timezone.utc)).total_seconds()
        ) < 120
        cursor.execute(
            "INSERT INTO atividade_base(nome_conceito) VALUES('Default stamp') "
            "RETURNING created_at"
        )
        default_value = cursor.fetchone()[0]
        assert re.fullmatch(r"\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}", default_value)
        first = value
        cursor.execute("SELECT pg_sleep(1.1)")
        cursor.execute("SELECT sgaa_utcnow_text()")
        second = cursor.fetchone()[0]
        assert first < second
        delta = datetime.strptime(second, "%Y-%m-%d %H:%M:%S") - datetime.strptime(
            first, "%Y-%m-%d %H:%M:%S"
        )
        assert delta >= timedelta(seconds=1)
    connection.commit()


def test_datetime_text_valid_helper_is_catalog_stable(provisioned_schema):
    """The corrected STABLE declaration must be visible in pg_proc."""
    connection, schema = provisioned_schema
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT p.provolatile FROM pg_catalog.pg_proc p "
            "JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace "
            "WHERE n.nspname = current_schema() AND p.proname = %s",
            ("sgaa_datetime_text_valid",),
        )
        assert cursor.fetchone()[0] == "s"
    connection.rollback()


# ---------------------------------------------------------------------------
# 10. trigger behaviour: all eleven
# ---------------------------------------------------------------------------


def test_trigger_prev_same_eixo_insert_and_update(provisioned_schema):
    connection, schema = provisioned_schema
    with connection.cursor() as cursor:
        base, aac_version = _seed_base_version(cursor)
        _assert_refused(
            connection,
            "atividade_versao",
            "INSERT INTO atividade_versao(atividade_base_id,eixo,numero_versao,status,"
            "versao_anterior_id) VALUES(%s,'AEU',2,'ativa',%s)",
            (base, aac_version),
        )
        aeu_version = _insert_version(cursor, base, "AEU", 2)
        same_eixo = _insert_version(cursor, base, "AAC", 3, predecessor=aac_version)
        _assert_refused(
            connection,
            "atividade_versao",
            "UPDATE atividade_versao SET eixo='AEU' WHERE id=%s",
            (same_eixo,),
        )
        cursor.execute(
            "UPDATE atividade_versao SET observacao_admin='ok' WHERE id=%s",
            (same_eixo,),
        )
        assert aeu_version != same_eixo
    connection.commit()


def test_trigger_aac_para_aeu_insert_and_update(provisioned_schema):
    connection, schema = provisioned_schema
    with connection.cursor() as cursor:
        base, aac_version = _seed_base_version(cursor)
        aeu_version = _insert_version(cursor, base, "AEU", 2)
        _assert_refused(
            connection,
            "atividade_transicao",
            "INSERT INTO atividade_transicao(from_atividade_versao_id,"
            "to_atividade_versao_id,tipo_transicao,justificativa) "
            "VALUES(%s,%s,'aac_para_aeu',NULL)",
            (aac_version, aeu_version),
        )
        _assert_refused(
            connection,
            "atividade_transicao",
            "INSERT INTO atividade_transicao(from_atividade_versao_id,"
            "to_atividade_versao_id,tipo_transicao,justificativa) "
            "VALUES(NULL,NULL,'aac_para_aeu','x')",
            None,
        )
        _assert_refused(
            connection,
            "atividade_transicao",
            "INSERT INTO atividade_transicao(from_atividade_versao_id,"
            "to_atividade_versao_id,tipo_transicao,justificativa) "
            "VALUES(%s,%s,'aac_para_aeu','x')",
            (aac_version, aac_version),
        )
        cursor.execute(
            "INSERT INTO atividade_transicao(from_atividade_versao_id,"
            "to_atividade_versao_id,tipo_transicao,justificativa) "
            "VALUES(%s,%s,'aac_para_aeu','mudanca justificada') RETURNING id",
            (aac_version, aeu_version),
        )
        transition = cursor.fetchone()[0]
        _assert_refused(
            connection,
            "atividade_transicao",
            "UPDATE atividade_transicao SET justificativa='' WHERE id=%s",
            (transition,),
        )
        cursor.execute(
            "UPDATE atividade_transicao SET observacao_admin='ok' WHERE id=%s",
            (transition,),
        )
    connection.commit()


def test_trigger_requisicoes_snapshot_immutable(provisioned_schema):
    connection, schema = provisioned_schema
    with connection.cursor() as cursor:
        base, version = _seed_base_version(cursor)
        other = _insert_version(cursor, base, "AEU", 2)
        requisicao = _seed_requisicao(cursor, version)
        _assert_refused(
            connection,
            "requisicoes",
            "UPDATE requisicoes SET regra_snapshot_json='{\"other\":true}' WHERE id=%s",
            (requisicao,),
        )
        _assert_refused(
            connection,
            "requisicoes",
            "UPDATE requisicoes SET atividade_versao_id=%s WHERE id=%s",
            (other, requisicao),
        )
        cursor.execute(
            "UPDATE requisicoes SET observacao='ok' WHERE id=%s", (requisicao,)
        )
    connection.commit()


def test_trigger_requisicoes_turma_snapshot_insert_and_update(provisioned_schema):
    connection, schema = provisioned_schema
    with connection.cursor() as cursor:
        _seed_course_matrix_turma(cursor)
        base, version = _seed_base_version(cursor)
        _assert_refused(
            connection,
            "requisicoes",
            "INSERT INTO requisicoes(atividade_versao_id,data_solicitacao,data_evento,"
            "horas_solicitadas,status,regra_snapshot_json,turma_id_snapshot,"
            "turma_codigo_snapshot) VALUES(%s,'2026-01-10 10:00:00',"
            "'2026-01-10 10:00:00',4,'Pendente','{}',1,NULL)",
            (version,),
        )
        requisicao = _seed_requisicao(cursor, version)
        cursor.execute(
            "UPDATE requisicoes SET turma_id_snapshot=1,turma_codigo_snapshot='U5A-T1' "
            "WHERE id=%s",
            (requisicao,),
        )
        _assert_refused(
            connection,
            "requisicoes",
            "UPDATE requisicoes SET turma_codigo_snapshot='CHANGED' WHERE id=%s",
            (requisicao,),
        )
    connection.commit()


def test_trigger_requisicao_arquivos_custody_insert_and_update(provisioned_schema):
    connection, schema = provisioned_schema
    with connection.cursor() as cursor:
        base, version = _seed_base_version(cursor)
        requisicao = _seed_requisicao(cursor, version)
        _assert_refused(
            connection,
            "requisicao_arquivos",
            "INSERT INTO requisicao_arquivos(requisicao_id,filename,remote_file_id) "
            "VALUES(%s,'a.pdf','remote')",
            (requisicao,),
        )
        _assert_refused(
            connection,
            "requisicao_arquivos",
            "INSERT INTO requisicao_arquivos(requisicao_id,filename,provider,"
            "storage_status) VALUES(%s,'a.pdf','google','active')",
            (requisicao,),
        )
        _assert_refused(
            connection,
            "requisicao_arquivos",
            "INSERT INTO requisicao_arquivos(requisicao_id,filename,provider,"
            "storage_status,delete_started_at) "
            "VALUES(%s,'a.pdf','google','trashed','2026-01-10 10:00:00')",
            (requisicao,),
        )
        cursor.execute(
            "INSERT INTO requisicao_arquivos(requisicao_id,filename) "
            "VALUES(%s,'legacy.pdf') RETURNING id",
            (requisicao,),
        )
        arquivo = cursor.fetchone()[0]
        cursor.execute(
            "UPDATE requisicao_arquivos SET label='ok' WHERE id=%s", (arquivo,)
        )
    connection.commit()


def test_trigger_admin_arquivos_custody_insert_and_update(provisioned_schema):
    connection, schema = provisioned_schema
    with connection.cursor() as cursor:
        _assert_refused(
            connection,
            "admin_arquivos",
            "INSERT INTO admin_arquivos(titulo,filename,remote_file_id) "
            "VALUES('A','a.pdf','remote')",
            None,
        )
        _assert_refused(
            connection,
            "admin_arquivos",
            "INSERT INTO admin_arquivos(titulo,filename,operation_key) "
            "VALUES('A','a.pdf','op-1')",
            None,
        )
        _assert_refused(
            connection,
            "admin_arquivos",
            "INSERT INTO admin_arquivos(titulo,filename,failure_code) "
            "VALUES('A','a.pdf','REPLACEMENT_FAILED')",
            None,
        )
        cursor.execute(
            "INSERT INTO admin_arquivos(titulo,filename) VALUES('A','a.pdf') "
            "RETURNING id"
        )
        arquivo = cursor.fetchone()[0]
        cursor.execute("UPDATE admin_arquivos SET titulo='B' WHERE id=%s", (arquivo,))
    connection.commit()


# ---------------------------------------------------------------------------
# 11-12. validator: read-only, valid pass, mutation probes
# ---------------------------------------------------------------------------


def test_validate_pg_schema_is_read_only_and_passes_valid_schema(provisioned_schema):
    connection, schema = provisioned_schema
    pg = _pg()
    before = _catalog_snapshot(connection)
    assert _scalar(connection, "SELECT pg_current_xact_id_if_assigned()") is None
    result = pg.validate_pg_schema(connection)
    assert result["schema_epoch"] == pg.PG_SCHEMA_EPOCH
    assert result["schema_version"] == pg.PG_SCHEMA_VERSION
    assert result["contract_sha256"] == pg.PG_CONTRACT_SHA256
    assert _scalar(connection, "SELECT pg_current_xact_id_if_assigned()") is None
    assert _catalog_snapshot(connection) == before
    connection.rollback()


@pytest.mark.parametrize(
    "mutation",
    [
        "ALTER TABLE usuarios DROP COLUMN foto_perfil",
        "ALTER TABLE usuarios DROP CONSTRAINT ck_usuarios_tipo",
        "ALTER TABLE usuarios ALTER COLUMN id DROP IDENTITY",
        "DROP TRIGGER trg_atividade_versao_prev_same_eixo_insert ON atividade_versao",
        "DROP INDEX ux_req_email_eventos_pendente",
        "DROP INDEX idx_usuarios_email",
        "ALTER TABLE alunos DROP CONSTRAINT fk_alunos_turma_id",
        "DROP TABLE requisicao_email_eventos CASCADE",
        "ALTER TABLE reportes_captura DROP CONSTRAINT ck_reportes_captura_conteudo",
        "ALTER TABLE alunos_foto DROP CONSTRAINT fk_alunos_foto_aluno_id",
        "ALTER TABLE usuarios_foto ALTER COLUMN conteudo TYPE text",
        "UPDATE pg_schema_meta SET contract_sha256 = repeat('0', 64)",
        "UPDATE pg_schema_meta SET schema_version = 11",
        "UPDATE pg_schema_meta SET schema_epoch = 'other'",
        "DELETE FROM pg_schema_meta",
    ],
)
def test_validator_detects_material_mutations(provisioned_schema, mutation):
    connection, schema = provisioned_schema
    pg = _pg()
    with connection.cursor() as cursor:
        cursor.execute(mutation)
    with pytest.raises(pg.PostgresSchemaError):
        pg.validate_pg_schema(connection)
    connection.rollback()
    pg.validate_pg_schema(connection)
    connection.rollback()


def test_validator_detects_wrong_fk_action(provisioned_schema):
    connection, schema = provisioned_schema
    pg = _pg()
    with connection.cursor() as cursor:
        cursor.execute("ALTER TABLE alunos DROP CONSTRAINT fk_alunos_turma_id")
        cursor.execute(
            "ALTER TABLE alunos ADD CONSTRAINT fk_alunos_turma_id FOREIGN KEY "
            "(turma_id) REFERENCES turmas(id) ON DELETE NO ACTION"
        )
    with pytest.raises(pg.PostgresSchemaError):
        pg.validate_pg_schema(connection)
    connection.rollback()
    pg.validate_pg_schema(connection)
    connection.rollback()


# ---------------------------------------------------------------------------
# 13. constraint diagnostics carry the explicit names
# ---------------------------------------------------------------------------


def test_constraint_diagnostics_expose_explicit_names(provisioned_schema):
    connection, schema = provisioned_schema
    with connection.cursor() as cursor:
        cursor.execute(
            "INSERT INTO usuarios(nome,email,senha,tipo) "
            "VALUES('A','dup@u5a.test','hash','admin')"
        )
    _assert_constraint_violation(
        connection,
        "INSERT INTO usuarios(nome,email,senha,tipo) "
        "VALUES('B','dup@u5a.test','hash','admin')",
        None,
        psycopg.errors.UniqueViolation,
        "uq_usuarios_email",
    )
    _assert_constraint_violation(
        connection,
        "INSERT INTO usuarios(nome,email,senha,tipo) "
        "VALUES('C','bad@u5a.test','hash','root')",
        None,
        psycopg.errors.CheckViolation,
        "ck_usuarios_tipo",
    )
    not_null_error = _probe_sqlstate(
        connection,
        "INSERT INTO usuarios(nome,email,senha) "
        "VALUES('D','null@u5a.test','hash')",
    )
    assert isinstance(not_null_error, psycopg.errors.NotNullViolation)
    _assert_constraint_violation(
        connection,
        "INSERT INTO alunos(nome,matricula,turma_id) "
        "VALUES('A','M-1',999999)",
        None,
        psycopg.errors.ForeignKeyViolation,
        "fk_alunos_turma_id",
    )
    connection.rollback()


# ---------------------------------------------------------------------------
# runtime boundary on a real server
# ---------------------------------------------------------------------------


def test_init_db_postgres_validates_only(provisioned_public, monkeypatch):
    import main
    from app import db as app_db
    import app.prod1_schema as prod1_schema

    monkeypatch.setattr(app_db, "DATABASE_URL", provisioned_public)

    def forbidden(*args, **kwargs):  # pragma: no cover - must never run
        raise AssertionError("SQLite bootstrap must not run on PostgreSQL")

    monkeypatch.setattr(app_db, "apply_schema_migrations", forbidden)
    monkeypatch.setattr(app_db, "apply_early_schema_migrations", forbidden)
    monkeypatch.setattr(prod1_schema, "bootstrap_prod1_schema", forbidden)

    inspector = _connect(provisioned_public)
    before = _catalog_snapshot(inspector)
    inspector.close()
    with main.app.app_context():
        app_db.init_db()
        app_db.close_db_connection(None)
    inspector = _connect(provisioned_public)
    assert _catalog_snapshot(inspector) == before
    inspector.close()


def test_init_db_postgres_fails_clean_without_provisioning(empty_database, monkeypatch):
    import main
    from app import db as app_db

    monkeypatch.setattr(app_db, "DATABASE_URL", empty_database)
    with main.app.app_context():
        with pytest.raises(RuntimeError) as excinfo:
            app_db.init_db()
        app_db.close_db_connection(None)
    assert "provision" in str(excinfo.value).lower()
    inspector = _connect(empty_database)
    tables = inspector.execute(
        "SELECT count(*) FROM pg_catalog.pg_class c "
        "JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace "
        "WHERE n.nspname='public' AND c.relkind IN ('r','p')"
    ).fetchone()[0]
    assert tables == 0
    inspector.close()


def test_runtime_ensure_paths_do_not_execute_pg_ddl(provisioned_public, monkeypatch):
    import main
    from app import db as app_db
    from app import db_maintenance
    from presets_api import ensure_presets_schema

    monkeypatch.setattr(app_db, "DATABASE_URL", provisioned_public)
    inspector = _connect(provisioned_public)
    before = _catalog_snapshot(inspector)
    inspector.close()
    with main.app.app_context():
        connection = app_db.get_db_connection()
        app_db.ensure_app_settings_schema(connection)
        app_db.ensure_cloud_backup_schema(connection)
        app_db.ensure_turmas_matriz_schema(connection)
        db_maintenance.ensure_usuario_access_schema(connection)
        db_maintenance.ensure_reportes_table(connection)
        db_maintenance.ensure_admin_arquivos_table(connection)
        db_maintenance.ensure_admin_alertas_table(connection)
        db_maintenance.ensure_usuario_profile_schema(connection)
        db_maintenance.ensure_atividade_versioning_schema(connection)
        db_maintenance.ensure_matrizes_atividades_table(connection)
        db_maintenance.ensure_matriz_atividade_links_table(connection)
        ensure_presets_schema(connection)
        connection.rollback()
        app_db.close_db_connection(None)
    inspector = _connect(provisioned_public)
    assert _catalog_snapshot(inspector) == before
    assert _count(inspector, "configuracoes_acesso") == 0
    assert _count(inspector, "configuracoes_app") == 0
    inspector.close()
